import type { Metadata } from "next";
import "../globals.css";
import Footer from "@/components/guest/Footer";
import Navbar from "@/components/guest/Navbar";
import { Suspense } from "react";
import Loading from "./home/loading";

export const metadata: Metadata = {
  title: "Olshop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`flex flex-col justify-between h-screen`}>
      <Navbar />
      <Suspense fallback={<Loading />}>
        <div className="flex-1 container mt-32 mb-24">{children}</div>
      </Suspense>
      <Footer />
    </div>
  );
}
