import Footer from "@/components/client/Footer";
import Navbar from "@/components/client/Navbar";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Olshop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`flex flex-col justify-between h-screen`}>
      <Navbar />
      <div className="flex-1 container mt-28 mb-24">{children}</div>
      <Footer />
    </div>
  );
}
