import ToasterProvider from "@/providers/ToasterProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Olshop Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider>
          <div className="grid grid-cols-7">
            <aside className="self-start sticky top-0 col-span-1 bg-black h-[100vh]">
              <Sidebar />
            </aside>
            <main className="col-span-6 p-10">{children}</main>
          </div>
        </ToasterProvider>
      </body>
    </html>
  );
}
