import GlobalProvider from "@/providers/GlobalProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { authOptions } from "./api/auth/[...nextauth]/auth-options";
import { StoreProvider } from "@/providers/StoreProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Olshop Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <GlobalProvider session={session}>
            <main>{children}</main>
          </GlobalProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
